-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER.vhd
-- Created: 2013-05-14 21:08:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER
-- Source Path: QPSK_Transmit_v12a/TX_SYSTEM_TOP/TX_CORE_DELAYED_SUBSYSTEM/TX_CORE/GEN_MOD_SHAPED_TX_DATA_PACKET/GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        INITIALIZE_GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER :   IN    std_logic;
        GEN_MODULATED_TX_DATA_PACKET_EN_COUNT :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER;


ARCHITECTURE rtl OF GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER IS

  -- Signals
  SIGNAL Constant1_out1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant2_out1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch1_out1                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL Sum_add_temp                     : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Sum_out1                         : signed(7 DOWNTO 0);  -- int8
  SIGNAL Unit_Delay_out1                  : signed(7 DOWNTO 0);  -- int8
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL INITIALIZE_GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER_1 : std_logic;

BEGIN
  Constant1_out1 <= to_signed(1, 8);

  Constant2_out1 <= to_signed(0, 8);

  Sum_add_temp <= resize(Constant1_out1, 9) + resize(Switch1_out1, 9);
  
  Sum_out1 <= "01111111" WHEN (Sum_add_temp(8) = '0') AND (Sum_add_temp(7) /= '0') ELSE
      "10000000" WHEN (Sum_add_temp(8) = '1') AND (Sum_add_temp(7) /= '1') ELSE
      Sum_add_temp(7 DOWNTO 0);

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_signed(0, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Sum_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  
  Compare_To_Constant3_out1 <= '1' WHEN Unit_Delay_out1 >= 8 ELSE
      '0';

  INITIALIZE_GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER_1 <= INITIALIZE_GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER OR Compare_To_Constant3_out1;

  
  Switch1_out1 <= Unit_Delay_out1 WHEN INITIALIZE_GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER_1 = '0' ELSE
      Constant2_out1;

  GEN_MODULATED_TX_DATA_PACKET_EN_COUNT <= std_logic_vector(Switch1_out1);

END rtl;

