-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\HEADER_MESSAGE_MUX_COUNTER.vhd
-- Created: 2013-05-14 21:08:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HEADER_MESSAGE_MUX_COUNTER
-- Source Path: QPSK_Transmit_v12a/TX_SYSTEM_TOP/TX_CORE_DELAYED_SUBSYSTEM/TX_CORE/GEN_MOD_SHAPED_TX_DATA_PACKET/GEN_MODULATED_TX_DATA_PACKET/HEADER_MESSAGE_MUX_COUNTER
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HEADER_MESSAGE_MUX_COUNTER IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        INITIALIZE_HEADER_MESSAGE_MUX_COUNTER :   IN    std_logic;
        HEADER_MESSAGE_MUX_COUNT          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END HEADER_MESSAGE_MUX_COUNTER;


ARCHITECTURE rtl OF HEADER_MESSAGE_MUX_COUNTER IS

  -- Signals
  SIGNAL Constant1_out1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant2_out1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant2_out1_dtc               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch1_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Sum_add_cast                     : signed(33 DOWNTO 0);  -- sfix34
  SIGNAL Sum_add_temp                     : signed(33 DOWNTO 0);  -- sfix34
  SIGNAL Sum_out1                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL INITIALIZE_HEADER_MESSAGE_MUX_COUNTER_1 : std_logic;

BEGIN
  Constant1_out1 <= to_signed(1, 8);

  Constant2_out1 <= to_signed(0, 8);

  Constant2_out1_dtc <= unsigned(resize(Constant2_out1, 32));

  Sum_add_cast <= signed(resize(Switch1_out1, 34));
  Sum_add_temp <= resize(Constant1_out1, 34) + Sum_add_cast;
  
  Sum_out1 <= "11111111111111111111111111111111" WHEN (Sum_add_temp(33) = '0') AND (Sum_add_temp(32) /= '0') ELSE
      "00000000000000000000000000000000" WHEN Sum_add_temp(33) = '1' ELSE
      unsigned(Sum_add_temp(31 DOWNTO 0));

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Sum_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  
  Compare_To_Constant3_out1 <= '1' WHEN Unit_Delay_out1 >= 1024 ELSE
      '0';

  INITIALIZE_HEADER_MESSAGE_MUX_COUNTER_1 <= INITIALIZE_HEADER_MESSAGE_MUX_COUNTER OR Compare_To_Constant3_out1;

  
  Switch1_out1 <= Unit_Delay_out1 WHEN INITIALIZE_HEADER_MESSAGE_MUX_COUNTER_1 = '0' ELSE
      Constant2_out1_dtc;

  HEADER_MESSAGE_MUX_COUNT <= std_logic_vector(Switch1_out1);

END rtl;

