-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\TX_CORE.vhd
-- Created: 2013-05-14 21:08:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TX_CORE
-- Source Path: QPSK_Transmit_v12a/TX_SYSTEM_TOP/TX_CORE_DELAYED_SUBSYSTEM/TX_CORE
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TX_CORE IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        MESSAGE_DATA_BYTE                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        FIFO_EMPTY                        :   IN    std_logic;
        INITIALIZE_TX_CORE                :   IN    std_logic;
        FIFO_RD_EN                        :   OUT   std_logic;
        MODULATED_SHAPED_I                :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        MODULATED_SHAPED_Q                :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
        );
END TX_CORE;


ARCHITECTURE rtl OF TX_CORE IS

  -- Component Declarations
  COMPONENT GEN_MOD_SHAPED_TX_DATA_PACKET
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          MESSAGE_DATA_BYTE               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          INITIALIZE_TX_CORE              :   IN    std_logic;
          Enable                          :   IN    std_logic;
          FIFO_RD_EN                      :   OUT   std_logic;
          MODULATED_SHAPED_I              :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          MODULATED_SHAPED_Q              :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : GEN_MOD_SHAPED_TX_DATA_PACKET
    USE ENTITY work.GEN_MOD_SHAPED_TX_DATA_PACKET(rtl);

  -- Signals
  SIGNAL GEN_MOD_SHAPED_TX_DATA_PACKET_out1 : std_logic;
  SIGNAL GEN_MOD_SHAPED_TX_DATA_PACKET_out2 : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL GEN_MOD_SHAPED_TX_DATA_PACKET_out3 : std_logic_vector(11 DOWNTO 0);  -- ufix12

BEGIN
  u_GEN_MOD_SHAPED_TX_DATA_PACKET : GEN_MOD_SHAPED_TX_DATA_PACKET
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              MESSAGE_DATA_BYTE => MESSAGE_DATA_BYTE,  -- uint8
              INITIALIZE_TX_CORE => INITIALIZE_TX_CORE,
              Enable => FIFO_EMPTY,
              FIFO_RD_EN => GEN_MOD_SHAPED_TX_DATA_PACKET_out1,
              MODULATED_SHAPED_I => GEN_MOD_SHAPED_TX_DATA_PACKET_out2,  -- sfix12_En11
              MODULATED_SHAPED_Q => GEN_MOD_SHAPED_TX_DATA_PACKET_out3  -- sfix12_En11
              );

  FIFO_RD_EN <= GEN_MOD_SHAPED_TX_DATA_PACKET_out1;

  MODULATED_SHAPED_I <= GEN_MOD_SHAPED_TX_DATA_PACKET_out2;

  MODULATED_SHAPED_Q <= GEN_MOD_SHAPED_TX_DATA_PACKET_out3;

END rtl;

