-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\TX_SYSTEM_TOP.vhd
-- Created: 2013-05-14 21:08:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- TXD                           ce_out        1
-- TX_IQ_SEL                     ce_out        1
-- FIFO_RD_EN                    ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TX_SYSTEM_TOP
-- Source Path: QPSK_Transmit_v12a/TX_SYSTEM_TOP
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TX_SYSTEM_TOP IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        MESSAGE_DATA_BYTE                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        FIFO_EMPTY                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        TXD                               :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        TX_IQ_SEL                         :   OUT   std_logic;  -- ufix1
        FIFO_RD_EN                        :   OUT   std_logic
        );
END TX_SYSTEM_TOP;


ARCHITECTURE rtl OF TX_SYSTEM_TOP IS

  -- Component Declarations
  COMPONENT TX_CORE_ENABLE_COUNTER
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          INITIALIZE_TX_CORE_ENABLE_COUNTER :   IN    std_logic;
          TX_CORE_ENABLE_COUNT            :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT TX_CORE_DELAYED_SUBSYSTEM
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          MESSAGE_DATA_BYTE               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          FIFO_EMPTY                      :   IN    std_logic;
          Enable                          :   IN    std_logic;
          FIFO_RD_EN                      :   OUT   std_logic;
          MODULATED_SHAPED_I              :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          MODULATED_SHAPED_Q              :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : TX_CORE_ENABLE_COUNTER
    USE ENTITY work.TX_CORE_ENABLE_COUNTER(rtl);

  FOR ALL : TX_CORE_DELAYED_SUBSYSTEM
    USE ENTITY work.TX_CORE_DELAYED_SUBSYSTEM(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL TXD_INTERLACING_COUNTER_count    : std_logic;  -- ufix1
  SIGNAL TXD_INTERLACING_COUNTER_out1     : std_logic;  -- ufix1
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL TX_CORE_ENABLE_COUNTER_out1      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL TX_CORE_ENABLE_COUNTER_out1_unsigned : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL TX_CORE_DELAYED_SUBSYSTEM_out1   : std_logic;
  SIGNAL TX_CORE_DELAYED_SUBSYSTEM_out2   : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL TX_CORE_DELAYED_SUBSYSTEM_out3   : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL TX_CORE_DELAYED_SUBSYSTEM_out3_signed : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL TX_CORE_DELAYED_SUBSYSTEM_out2_signed : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL TXD_INTERLACING_MUX_out1         : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL FIFO_RD_EN_Z1_DELAY_out1         : std_logic;

BEGIN
  u_TX_CORE_ENABLE_COUNTER : TX_CORE_ENABLE_COUNTER
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              INITIALIZE_TX_CORE_ENABLE_COUNTER => Constant1_out1,
              TX_CORE_ENABLE_COUNT => TX_CORE_ENABLE_COUNTER_out1  -- uint32
              );

  u_TX_CORE_DELAYED_SUBSYSTEM : TX_CORE_DELAYED_SUBSYSTEM
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              MESSAGE_DATA_BYTE => MESSAGE_DATA_BYTE,  -- uint8
              FIFO_EMPTY => FIFO_EMPTY,
              Enable => Compare_To_Constant_out1,
              FIFO_RD_EN => TX_CORE_DELAYED_SUBSYSTEM_out1,
              MODULATED_SHAPED_I => TX_CORE_DELAYED_SUBSYSTEM_out2,  -- sfix12_En11
              MODULATED_SHAPED_Q => TX_CORE_DELAYED_SUBSYSTEM_out3  -- sfix12_En11
              );

  enb <= clk_enable;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  TXD_INTERLACING_COUNTER_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      TXD_INTERLACING_COUNTER_count <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        TXD_INTERLACING_COUNTER_count <=  NOT TXD_INTERLACING_COUNTER_count;
      END IF;
    END IF;
  END PROCESS TXD_INTERLACING_COUNTER_process;

  TXD_INTERLACING_COUNTER_out1 <= TXD_INTERLACING_COUNTER_count;

  Constant1_out1 <= '0';

  TX_CORE_ENABLE_COUNTER_out1_unsigned <= unsigned(TX_CORE_ENABLE_COUNTER_out1);

  
  Compare_To_Constant_out1 <= '1' WHEN TX_CORE_ENABLE_COUNTER_out1_unsigned > 2 ELSE
      '0';

  TX_CORE_DELAYED_SUBSYSTEM_out3_signed <= signed(TX_CORE_DELAYED_SUBSYSTEM_out3);

  TX_CORE_DELAYED_SUBSYSTEM_out2_signed <= signed(TX_CORE_DELAYED_SUBSYSTEM_out2);

  
  TXD_INTERLACING_MUX_out1 <= TX_CORE_DELAYED_SUBSYSTEM_out3_signed WHEN TXD_INTERLACING_COUNTER_out1 = '0' ELSE
      TX_CORE_DELAYED_SUBSYSTEM_out2_signed;

  TXD <= std_logic_vector(TXD_INTERLACING_MUX_out1);

  FIFO_RD_EN_Z1_DELAY_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FIFO_RD_EN_Z1_DELAY_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FIFO_RD_EN_Z1_DELAY_out1 <= TX_CORE_DELAYED_SUBSYSTEM_out1;
      END IF;
    END IF;
  END PROCESS FIFO_RD_EN_Z1_DELAY_process;


  ce_out <= clk_enable;

  TX_IQ_SEL <= TXD_INTERLACING_COUNTER_out1;

  FIFO_RD_EN <= FIFO_RD_EN_Z1_DELAY_out1;

END rtl;

