-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\qpsk_srrc.vhd
-- Created: 2013-05-25 17:08:52
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: qpsk_srrc
-- Source Path: QPSK_Transmit_v12c/TX_SYSTEM_TOP/TX_CORE_DELAYED_SUBSYSTEM/TX_CORE/GEN_MOD_SHAPED_TX_DATA_PACKET/qpsk_srrc
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.TX_SYSTEM_TOP_pkg.ALL;

ENTITY qpsk_srrc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        d_in_re                           :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        d_in_im                           :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        d_out_re                          :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        d_out_im                          :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
        );
END qpsk_srrc;


ARCHITECTURE rtl OF qpsk_srrc IS

  -- Signals
  SIGNAL tmp                              : vector_of_signed32(0 TO 15);  -- int32 [16]
  SIGNAL d_in_re_signed                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL d_in_im_signed                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL buf_re                           : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL buf_im                           : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL buf_re_1                         : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL buf_im_1                         : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL tmp_re                           : vector_of_signed3(0 TO 15);  -- sfix3 [16]
  SIGNAL tmp_im                           : vector_of_signed3(0 TO 15);  -- sfix3 [16]
  SIGNAL tmp_re_1                         : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL tmp_im_1                         : vector_of_signed3(0 TO 16);  -- sfix3 [17]
  SIGNAL tmp_1                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_2                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_2                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_3                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_3                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar                               : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr                               : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai                               : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci                               : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp1_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp1_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_4                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_im_4                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_3                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_5                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_5                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_4                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_6                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_6                         : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_1                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_1                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_1                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_1                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp2_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp2_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_7                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_im_7                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_re_8                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_im_8                         : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL tmp_re_9                         : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_im_9                         : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_5                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_10                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_10                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_11                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_11                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_2                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_2                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_2                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_2                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp3_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp3_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_12                        : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_im_12                        : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_re_13                        : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_im_13                        : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL tmp_re_14                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_im_14                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_7                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_15                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_15                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_16                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_16                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_3                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_3                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_3                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_3                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp4_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp4_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_17                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_im_17                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_re_18                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_im_18                        : signed(19 DOWNTO 0);  -- sfix20_En14
  SIGNAL tmp_re_19                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_im_19                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_9                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_20                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_20                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_21                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_21                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_4                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_4                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_4                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_4                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp5_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp5_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_22                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_im_22                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_re_23                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_im_23                        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL tmp_re_24                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_im_24                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_11                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_25                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_25                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_26                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_26                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_5                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_5                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_5                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_5                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp6_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp6_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_27                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_im_27                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_re_28                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_im_28                        : signed(21 DOWNTO 0);  -- sfix22_En14
  SIGNAL tmp_re_29                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_im_29                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_13                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_30                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_30                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_14                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_31                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_31                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_6                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_6                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_6                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_6                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp7_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp7_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_32                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_im_32                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_re_33                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_im_33                        : signed(22 DOWNTO 0);  -- sfix23_En14
  SIGNAL tmp_re_34                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_im_34                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_15                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_35                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_35                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_16                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_36                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_36                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_7                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_7                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_7                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_7                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp8_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp8_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_37                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_im_37                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_re_38                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_im_38                        : signed(23 DOWNTO 0);  -- sfix24_En14
  SIGNAL tmp_re_39                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_im_39                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_17                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_40                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_40                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_41                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_41                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_8                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_8                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_8                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_8                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp9_re                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp9_im                         : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_42                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_im_42                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_re_43                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_im_43                        : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL tmp_re_44                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_im_44                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_19                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_45                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_45                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_20                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_46                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_46                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_9                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_9                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_9                             : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_9                             : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp10_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp10_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_47                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_im_47                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_re_48                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_im_48                        : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL tmp_re_49                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_im_49                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_21                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_50                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_50                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_51                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_51                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_10                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_10                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_10                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_10                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp11_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp11_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_52                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_im_52                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_re_53                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_im_53                        : signed(26 DOWNTO 0);  -- sfix27_En14
  SIGNAL tmp_re_54                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_im_54                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_23                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_55                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_55                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_24                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_56                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_56                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_11                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_11                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_11                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_11                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp12_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp12_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_57                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_im_57                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_re_58                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_im_58                        : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL tmp_re_59                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_im_59                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_25                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_60                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_60                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_26                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_61                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_61                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_12                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_12                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_12                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_12                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp13_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp13_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_62                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_im_62                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_re_63                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_im_63                        : signed(28 DOWNTO 0);  -- sfix29_En14
  SIGNAL tmp_re_64                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_im_64                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_27                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_65                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_65                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_28                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_66                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_66                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_13                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_13                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_13                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_13                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp14_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp14_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_67                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_im_67                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_re_68                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_im_68                        : signed(29 DOWNTO 0);  -- sfix30_En14
  SIGNAL tmp_re_69                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_im_69                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_29                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_70                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_70                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_30                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_71                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_71                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_14                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_14                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_14                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_14                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp15_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp15_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_72                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_im_72                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_re_73                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_im_73                        : signed(30 DOWNTO 0);  -- sfix31_En14
  SIGNAL tmp_re_74                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_im_74                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_31                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_75                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_75                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_32                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_76                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_76                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_15                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_15                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_15                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_15                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp16_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp16_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_77                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_im_77                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_re_78                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_im_78                        : signed(31 DOWNTO 0);  -- sfix32_En14
  SIGNAL tmp_re_79                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL tmp_im_79                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL tmp_33                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_80                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_80                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_re_81                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL tmp_im_81                        : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ar_16                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL cr_16                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL ai_16                            : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL ci_16                            : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp17_re                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL temp17_im                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_re_82                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL tmp_im_82                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL tmp_re_83                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL tmp_im_83                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL result_re                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL result_im                        : signed(32 DOWNTO 0);  -- sfix33_En14
  SIGNAL d_out_re_1                       : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL d_out_im_1                       : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL d_out_re_2                       : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL d_out_im_2                       : signed(11 DOWNTO 0);  -- sfix12_En11

BEGIN
  --spssa

  tmp_gen: FOR t_0 IN 0 TO 15 GENERATE
    tmp(t_0) <= to_signed(1 + t_0, 32);
  END GENERATE tmp_gen;


  d_in_re_signed <= signed(d_in_re);

  d_in_im_signed <= signed(d_in_im);

  -- d_out = fi(buf*f, 1, 12, 0, fm);
  buf_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      buf_re_1 <= (OTHERS => to_signed(0, 3));
      buf_im_1 <= (OTHERS => to_signed(0, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        buf_re_1 <= buf_re;
        buf_im_1 <= buf_im;
      END IF;
    END IF;
  END PROCESS buf_reg_process;



  tmp_im_gen: FOR t_01 IN 0 TO 15 GENERATE
    tmp_re(t_01) <= buf_re_1(to_integer(tmp(t_01)));
    tmp_im(t_01) <= buf_im_1(to_integer(tmp(t_01)));
  END GENERATE tmp_im_gen;


  tmp_re_1(0 TO 15) <= tmp_re(0 TO 15);
  tmp_im_1(0 TO 15) <= tmp_im(0 TO 15);
  tmp_re_1(16) <= d_in_re_signed(2 DOWNTO 0);
  tmp_im_1(16) <= d_in_im_signed(2 DOWNTO 0);

  buf_re <= tmp_re_1;
  buf_im <= tmp_im_1;

  tmp_1 <= to_signed(0, 32);

  tmp_re_2 <= buf_re(to_integer(tmp_1));
  tmp_im_2 <= buf_im(to_integer(tmp_1));

  tmp_2 <= to_signed(0, 32);

  tmp_re_3 <= buf_re(to_integer(tmp_2));
  tmp_im_3 <= buf_im(to_integer(tmp_2));

  ar <= tmp_re_2;

  cr <= ar * to_signed(109, 14);

  ai <= tmp_im_3;

  ci <= ai * to_signed(109, 14);

  temp1_re <= cr;
  temp1_im <= ci;

  tmp_re_4 <= resize(temp1_re, 18);
  tmp_im_4 <= resize(temp1_im, 18);

  tmp_3 <= to_signed(1, 32);

  tmp_re_5 <= buf_re(to_integer(tmp_3));
  tmp_im_5 <= buf_im(to_integer(tmp_3));

  tmp_4 <= to_signed(1, 32);

  tmp_re_6 <= buf_re(to_integer(tmp_4));
  tmp_im_6 <= buf_im(to_integer(tmp_4));

  ar_1 <= tmp_re_5;

  cr_1 <= ar_1 * to_signed(-95, 14);

  ai_1 <= tmp_im_6;

  ci_1 <= ai_1 * to_signed(-95, 14);

  temp2_re <= cr_1;
  temp2_im <= ci_1;

  tmp_re_7 <= resize(temp2_re, 18);
  tmp_im_7 <= resize(temp2_im, 18);

  tmp_re_8 <= tmp_re_4 + tmp_re_7;
  tmp_im_8 <= tmp_im_4 + tmp_im_7;

  tmp_re_9 <= resize(tmp_re_8, 19);
  tmp_im_9 <= resize(tmp_im_8, 19);

  tmp_5 <= to_signed(3, 32);

  tmp_re_10 <= buf_re(to_integer(tmp_5));
  tmp_im_10 <= buf_im(to_integer(tmp_5));

  tmp_6 <= to_signed(3, 32);

  tmp_re_11 <= buf_re(to_integer(tmp_6));
  tmp_im_11 <= buf_im(to_integer(tmp_6));

  ar_2 <= tmp_re_10;

  cr_2 <= ar_2 * to_signed(-194, 14);

  ai_2 <= tmp_im_11;

  ci_2 <= ai_2 * to_signed(-194, 14);

  temp3_re <= cr_2;
  temp3_im <= ci_2;

  tmp_re_12 <= resize(temp3_re, 19);
  tmp_im_12 <= resize(temp3_im, 19);

  tmp_re_13 <= tmp_re_9 + tmp_re_12;
  tmp_im_13 <= tmp_im_9 + tmp_im_12;

  tmp_re_14 <= resize(tmp_re_13, 20);
  tmp_im_14 <= resize(tmp_im_13, 20);

  tmp_7 <= to_signed(3, 32);

  tmp_re_15 <= buf_re(to_integer(tmp_7));
  tmp_im_15 <= buf_im(to_integer(tmp_7));

  tmp_8 <= to_signed(3, 32);

  tmp_re_16 <= buf_re(to_integer(tmp_8));
  tmp_im_16 <= buf_im(to_integer(tmp_8));

  ar_3 <= tmp_re_15;

  cr_3 <= ar_3 * to_signed(337, 14);

  ai_3 <= tmp_im_16;

  ci_3 <= ai_3 * to_signed(337, 14);

  temp4_re <= cr_3;
  temp4_im <= ci_3;

  tmp_re_17 <= resize(temp4_re, 20);
  tmp_im_17 <= resize(temp4_im, 20);

  tmp_re_18 <= tmp_re_14 + tmp_re_17;
  tmp_im_18 <= tmp_im_14 + tmp_im_17;

  tmp_re_19 <= resize(tmp_re_18, 21);
  tmp_im_19 <= resize(tmp_im_18, 21);

  tmp_9 <= to_signed(4, 32);

  tmp_re_20 <= buf_re(to_integer(tmp_9));
  tmp_im_20 <= buf_im(to_integer(tmp_9));

  tmp_10 <= to_signed(4, 32);

  tmp_re_21 <= buf_re(to_integer(tmp_10));
  tmp_im_21 <= buf_im(to_integer(tmp_10));

  ar_4 <= tmp_re_20;

  cr_4 <= ar_4 * to_signed(274, 14);

  ai_4 <= tmp_im_21;

  ci_4 <= ai_4 * to_signed(274, 14);

  temp5_re <= cr_4;
  temp5_im <= ci_4;

  tmp_re_22 <= resize(temp5_re, 21);
  tmp_im_22 <= resize(temp5_im, 21);

  tmp_re_23 <= tmp_re_19 + tmp_re_22;
  tmp_im_23 <= tmp_im_19 + tmp_im_22;

  tmp_re_24 <= resize(tmp_re_23, 22);
  tmp_im_24 <= resize(tmp_im_23, 22);

  tmp_11 <= to_signed(5, 32);

  tmp_re_25 <= buf_re(to_integer(tmp_11));
  tmp_im_25 <= buf_im(to_integer(tmp_11));

  tmp_12 <= to_signed(5, 32);

  tmp_re_26 <= buf_re(to_integer(tmp_12));
  tmp_im_26 <= buf_im(to_integer(tmp_12));

  ar_5 <= tmp_re_25;

  cr_5 <= ar_5 * to_signed(-880, 14);

  ai_5 <= tmp_im_26;

  ci_5 <= ai_5 * to_signed(-880, 14);

  temp6_re <= cr_5;
  temp6_im <= ci_5;

  tmp_re_27 <= resize(temp6_re, 22);
  tmp_im_27 <= resize(temp6_im, 22);

  tmp_re_28 <= tmp_re_24 + tmp_re_27;
  tmp_im_28 <= tmp_im_24 + tmp_im_27;

  tmp_re_29 <= resize(tmp_re_28, 23);
  tmp_im_29 <= resize(tmp_im_28, 23);

  tmp_13 <= to_signed(6, 32);

  tmp_re_30 <= buf_re(to_integer(tmp_13));
  tmp_im_30 <= buf_im(to_integer(tmp_13));

  tmp_14 <= to_signed(6, 32);

  tmp_re_31 <= buf_re(to_integer(tmp_14));
  tmp_im_31 <= buf_im(to_integer(tmp_14));

  ar_6 <= tmp_re_30;

  cr_6 <= ar_6 * to_signed(-332, 14);

  ai_6 <= tmp_im_31;

  ci_6 <= ai_6 * to_signed(-332, 14);

  temp7_re <= cr_6;
  temp7_im <= ci_6;

  tmp_re_32 <= resize(temp7_re, 23);
  tmp_im_32 <= resize(temp7_im, 23);

  tmp_re_33 <= tmp_re_29 + tmp_re_32;
  tmp_im_33 <= tmp_im_29 + tmp_im_32;

  tmp_re_34 <= resize(tmp_re_33, 24);
  tmp_im_34 <= resize(tmp_im_33, 24);

  tmp_15 <= to_signed(7, 32);

  tmp_re_35 <= buf_re(to_integer(tmp_15));
  tmp_im_35 <= buf_im(to_integer(tmp_15));

  tmp_16 <= to_signed(7, 32);

  tmp_re_36 <= buf_re(to_integer(tmp_16));
  tmp_im_36 <= buf_im(to_integer(tmp_16));

  ar_7 <= tmp_re_35;

  cr_7 <= ar_7 * to_signed(3211, 14);

  ai_7 <= tmp_im_36;

  ci_7 <= ai_7 * to_signed(3211, 14);

  temp8_re <= cr_7;
  temp8_im <= ci_7;

  tmp_re_37 <= resize(temp8_re, 24);
  tmp_im_37 <= resize(temp8_im, 24);

  tmp_re_38 <= tmp_re_34 + tmp_re_37;
  tmp_im_38 <= tmp_im_34 + tmp_im_37;

  tmp_re_39 <= resize(tmp_re_38, 25);
  tmp_im_39 <= resize(tmp_im_38, 25);

  tmp_17 <= to_signed(8, 32);

  tmp_re_40 <= buf_re(to_integer(tmp_17));
  tmp_im_40 <= buf_im(to_integer(tmp_17));

  tmp_18 <= to_signed(8, 32);

  tmp_re_41 <= buf_re(to_integer(tmp_18));
  tmp_im_41 <= buf_im(to_integer(tmp_18));

  ar_8 <= tmp_re_40;

  cr_8 <= ar_8 * to_signed(5518, 14);

  ai_8 <= tmp_im_41;

  ci_8 <= ai_8 * to_signed(5518, 14);

  temp9_re <= cr_8;
  temp9_im <= ci_8;

  tmp_re_42 <= resize(temp9_re, 25);
  tmp_im_42 <= resize(temp9_im, 25);

  tmp_re_43 <= tmp_re_39 + tmp_re_42;
  tmp_im_43 <= tmp_im_39 + tmp_im_42;

  tmp_re_44 <= resize(tmp_re_43, 26);
  tmp_im_44 <= resize(tmp_im_43, 26);

  tmp_19 <= to_signed(9, 32);

  tmp_re_45 <= buf_re(to_integer(tmp_19));
  tmp_im_45 <= buf_im(to_integer(tmp_19));

  tmp_20 <= to_signed(9, 32);

  tmp_re_46 <= buf_re(to_integer(tmp_20));
  tmp_im_46 <= buf_im(to_integer(tmp_20));

  ar_9 <= tmp_re_45;

  cr_9 <= ar_9 * to_signed(3211, 14);

  ai_9 <= tmp_im_46;

  ci_9 <= ai_9 * to_signed(3211, 14);

  temp10_re <= cr_9;
  temp10_im <= ci_9;

  tmp_re_47 <= resize(temp10_re, 26);
  tmp_im_47 <= resize(temp10_im, 26);

  tmp_re_48 <= tmp_re_44 + tmp_re_47;
  tmp_im_48 <= tmp_im_44 + tmp_im_47;

  tmp_re_49 <= resize(tmp_re_48, 27);
  tmp_im_49 <= resize(tmp_im_48, 27);

  tmp_21 <= to_signed(10, 32);

  tmp_re_50 <= buf_re(to_integer(tmp_21));
  tmp_im_50 <= buf_im(to_integer(tmp_21));

  tmp_22 <= to_signed(10, 32);

  tmp_re_51 <= buf_re(to_integer(tmp_22));
  tmp_im_51 <= buf_im(to_integer(tmp_22));

  ar_10 <= tmp_re_50;

  cr_10 <= ar_10 * to_signed(-332, 14);

  ai_10 <= tmp_im_51;

  ci_10 <= ai_10 * to_signed(-332, 14);

  temp11_re <= cr_10;
  temp11_im <= ci_10;

  tmp_re_52 <= resize(temp11_re, 27);
  tmp_im_52 <= resize(temp11_im, 27);

  tmp_re_53 <= tmp_re_49 + tmp_re_52;
  tmp_im_53 <= tmp_im_49 + tmp_im_52;

  tmp_re_54 <= resize(tmp_re_53, 28);
  tmp_im_54 <= resize(tmp_im_53, 28);

  tmp_23 <= to_signed(11, 32);

  tmp_re_55 <= buf_re(to_integer(tmp_23));
  tmp_im_55 <= buf_im(to_integer(tmp_23));

  tmp_24 <= to_signed(11, 32);

  tmp_re_56 <= buf_re(to_integer(tmp_24));
  tmp_im_56 <= buf_im(to_integer(tmp_24));

  ar_11 <= tmp_re_55;

  cr_11 <= ar_11 * to_signed(-880, 14);

  ai_11 <= tmp_im_56;

  ci_11 <= ai_11 * to_signed(-880, 14);

  temp12_re <= cr_11;
  temp12_im <= ci_11;

  tmp_re_57 <= resize(temp12_re, 28);
  tmp_im_57 <= resize(temp12_im, 28);

  tmp_re_58 <= tmp_re_54 + tmp_re_57;
  tmp_im_58 <= tmp_im_54 + tmp_im_57;

  tmp_re_59 <= resize(tmp_re_58, 29);
  tmp_im_59 <= resize(tmp_im_58, 29);

  tmp_25 <= to_signed(12, 32);

  tmp_re_60 <= buf_re(to_integer(tmp_25));
  tmp_im_60 <= buf_im(to_integer(tmp_25));

  tmp_26 <= to_signed(12, 32);

  tmp_re_61 <= buf_re(to_integer(tmp_26));
  tmp_im_61 <= buf_im(to_integer(tmp_26));

  ar_12 <= tmp_re_60;

  cr_12 <= ar_12 * to_signed(274, 14);

  ai_12 <= tmp_im_61;

  ci_12 <= ai_12 * to_signed(274, 14);

  temp13_re <= cr_12;
  temp13_im <= ci_12;

  tmp_re_62 <= resize(temp13_re, 29);
  tmp_im_62 <= resize(temp13_im, 29);

  tmp_re_63 <= tmp_re_59 + tmp_re_62;
  tmp_im_63 <= tmp_im_59 + tmp_im_62;

  tmp_re_64 <= resize(tmp_re_63, 30);
  tmp_im_64 <= resize(tmp_im_63, 30);

  tmp_27 <= to_signed(13, 32);

  tmp_re_65 <= buf_re(to_integer(tmp_27));
  tmp_im_65 <= buf_im(to_integer(tmp_27));

  tmp_28 <= to_signed(13, 32);

  tmp_re_66 <= buf_re(to_integer(tmp_28));
  tmp_im_66 <= buf_im(to_integer(tmp_28));

  ar_13 <= tmp_re_65;

  cr_13 <= ar_13 * to_signed(337, 14);

  ai_13 <= tmp_im_66;

  ci_13 <= ai_13 * to_signed(337, 14);

  temp14_re <= cr_13;
  temp14_im <= ci_13;

  tmp_re_67 <= resize(temp14_re, 30);
  tmp_im_67 <= resize(temp14_im, 30);

  tmp_re_68 <= tmp_re_64 + tmp_re_67;
  tmp_im_68 <= tmp_im_64 + tmp_im_67;

  tmp_re_69 <= resize(tmp_re_68, 31);
  tmp_im_69 <= resize(tmp_im_68, 31);

  tmp_29 <= to_signed(14, 32);

  tmp_re_70 <= buf_re(to_integer(tmp_29));
  tmp_im_70 <= buf_im(to_integer(tmp_29));

  tmp_30 <= to_signed(14, 32);

  tmp_re_71 <= buf_re(to_integer(tmp_30));
  tmp_im_71 <= buf_im(to_integer(tmp_30));

  ar_14 <= tmp_re_70;

  cr_14 <= ar_14 * to_signed(-194, 14);

  ai_14 <= tmp_im_71;

  ci_14 <= ai_14 * to_signed(-194, 14);

  temp15_re <= cr_14;
  temp15_im <= ci_14;

  tmp_re_72 <= resize(temp15_re, 31);
  tmp_im_72 <= resize(temp15_im, 31);

  tmp_re_73 <= tmp_re_69 + tmp_re_72;
  tmp_im_73 <= tmp_im_69 + tmp_im_72;

  tmp_re_74 <= resize(tmp_re_73, 32);
  tmp_im_74 <= resize(tmp_im_73, 32);

  tmp_31 <= to_signed(15, 32);

  tmp_re_75 <= buf_re(to_integer(tmp_31));
  tmp_im_75 <= buf_im(to_integer(tmp_31));

  tmp_32 <= to_signed(15, 32);

  tmp_re_76 <= buf_re(to_integer(tmp_32));
  tmp_im_76 <= buf_im(to_integer(tmp_32));

  ar_15 <= tmp_re_75;

  cr_15 <= ar_15 * to_signed(-95, 14);

  ai_15 <= tmp_im_76;

  ci_15 <= ai_15 * to_signed(-95, 14);

  temp16_re <= cr_15;
  temp16_im <= ci_15;

  tmp_re_77 <= resize(temp16_re, 32);
  tmp_im_77 <= resize(temp16_im, 32);

  tmp_re_78 <= tmp_re_74 + tmp_re_77;
  tmp_im_78 <= tmp_im_74 + tmp_im_77;

  tmp_re_79 <= resize(tmp_re_78, 33);
  tmp_im_79 <= resize(tmp_im_78, 33);

  tmp_33 <= to_signed(16, 32);

  tmp_re_80 <= buf_re(to_integer(tmp_33));
  tmp_im_80 <= buf_im(to_integer(tmp_33));

  tmp_34 <= to_signed(16, 32);

  tmp_re_81 <= buf_re(to_integer(tmp_34));
  tmp_im_81 <= buf_im(to_integer(tmp_34));

  ar_16 <= tmp_re_80;

  cr_16 <= ar_16 * to_signed(109, 14);

  ai_16 <= tmp_im_81;

  ci_16 <= ai_16 * to_signed(109, 14);

  temp17_re <= cr_16;
  temp17_im <= ci_16;

  tmp_re_82 <= resize(temp17_re, 33);
  tmp_im_82 <= resize(temp17_im, 33);

  tmp_re_83 <= tmp_re_79 + tmp_re_82;
  tmp_im_83 <= tmp_im_79 + tmp_im_82;

  result_re <= tmp_re_83;
  result_im <= tmp_im_83;

  d_out_re_1 <= result_re(14 DOWNTO 3);
  d_out_im_1 <= result_im(14 DOWNTO 3);

  d_out_re_2 <= d_out_re_1;
  d_out_im_2 <= d_out_im_1;

  d_out_re <= std_logic_vector(d_out_re_2);

  d_out_im <= std_logic_vector(d_out_im_2);

END rtl;

