-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\FIFO_RD_ENABLE_LOGIC.vhd
-- Created: 2013-05-26 21:23:00
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FIFO_RD_ENABLE_LOGIC
-- Source Path: QPSK_system_v3g/TX_SYSTEM_TOP/FIFO_RD_ENABLE_LOGIC
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FIFO_RD_ENABLE_LOGIC IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        FIFO_RD_ENABLE_LOGIC_INPUT        :   IN    std_logic;
        FIFO_RD_ENABLE_LOGIC_OUTPUT       :   OUT   std_logic
        );
END FIFO_RD_ENABLE_LOGIC;


ARCHITECTURE rtl OF FIFO_RD_ENABLE_LOGIC IS

  -- Signals
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Bitwise_Operator_out1            : std_logic;

BEGIN
  
  Compare_To_Constant_out1 <= '1' WHEN FIFO_RD_ENABLE_LOGIC_INPUT = '1' ELSE
      '0';

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= FIFO_RD_ENABLE_LOGIC_INPUT;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN Delay_out1 = '0' ELSE
      '0';

  Bitwise_Operator_out1 <= Compare_To_Constant_out1 AND Compare_To_Constant1_out1;

  FIFO_RD_ENABLE_LOGIC_OUTPUT <= Bitwise_Operator_out1;

END rtl;

