-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER.vhd
-- Created: 2013-05-26 21:23:00
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER
-- Source Path: QPSK_system_v3g/TX_SYSTEM_TOP/TX_CORE_DELAYED_SUBSYSTEM/TX_CORE/GEN_MOD_SHAPED_TX_DATA_PACKET/GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        GEN_MODULATED_TX_DATA_PACKET_RESET :   IN    std_logic;
        GEN_MODULATED_TX_DATA_PACKET_EN_COUNT :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER;


ARCHITECTURE rtl OF GEN_MODULATED_TX_DATA_PACKET_EN_COUNTER IS

  -- Signals
  SIGNAL Constant3_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant4_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay1_out1                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Sum1_add_temp                    : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL Sum1_out1                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL GEN_MODULATED_TX_DATA_PACKET_RESET_1 : std_logic;
  SIGNAL Switch2_out1                     : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  Constant3_out1 <= to_unsigned(1, 32);

  Constant4_out1 <= to_unsigned(0, 32);

  Sum1_add_temp <= resize(Constant3_out1, 33) + resize(Unit_Delay1_out1, 33);
  
  Sum1_out1 <= "11111111111111111111111111111111" WHEN Sum1_add_temp(32) /= '0' ELSE
      Sum1_add_temp(31 DOWNTO 0);

  
  Compare_To_Constant_out1 <= '1' WHEN Unit_Delay1_out1 = 7 ELSE
      '0';

  GEN_MODULATED_TX_DATA_PACKET_RESET_1 <= GEN_MODULATED_TX_DATA_PACKET_RESET OR Compare_To_Constant_out1;

  
  Switch2_out1 <= Sum1_out1 WHEN GEN_MODULATED_TX_DATA_PACKET_RESET_1 = '0' ELSE
      Constant4_out1;

  Unit_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay1_out1 <= Switch2_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_process;


  GEN_MODULATED_TX_DATA_PACKET_EN_COUNT <= std_logic_vector(Unit_Delay1_out1);

END rtl;

