-- ------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\QPSK_SRRC
-- Created: 2013-05-26 21:23:00
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- ------------------------------------------------------------
-- 
-- 
-- ------------------------------------------------------------
-- 
-- Module: QPSK_SRRC
-- Source Path: /QPSK_SRRC
-- 
-- ------------------------------------------------------------
-- 
-- HDL Implementation    : Fully parallel


LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
ENTITY QPSK_SRRC IS
   PORT( clk                             :   IN    std_logic; 
         enb_gated                       :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         QPSK_SRRC_in_re                 :   IN    std_logic_vector(7 DOWNTO 0); -- sfix8
         QPSK_SRRC_in_im                 :   IN    std_logic_vector(7 DOWNTO 0); -- sfix8
         QPSK_SRRC_out_re                :   OUT   std_logic_vector(11 DOWNTO 0); -- sfix12_En11
         QPSK_SRRC_out_im                :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
         );

END QPSK_SRRC;


----------------------------------------------------------------
--Module Architecture: QPSK_SRRC
----------------------------------------------------------------
ARCHITECTURE rtl OF QPSK_SRRC IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(24 DOWNTO 0); -- sfix25_En11
  -- Constants
  CONSTANT coeff1                         : signed(11 DOWNTO 0) := to_signed(14, 12); -- sfix12_En11
  CONSTANT coeff2                         : signed(11 DOWNTO 0) := to_signed(-12, 12); -- sfix12_En11
  CONSTANT coeff3                         : signed(11 DOWNTO 0) := to_signed(-24, 12); -- sfix12_En11
  CONSTANT coeff4                         : signed(11 DOWNTO 0) := to_signed(42, 12); -- sfix12_En11
  CONSTANT coeff5                         : signed(11 DOWNTO 0) := to_signed(34, 12); -- sfix12_En11
  CONSTANT coeff6                         : signed(11 DOWNTO 0) := to_signed(-110, 12); -- sfix12_En11
  CONSTANT coeff7                         : signed(11 DOWNTO 0) := to_signed(-41, 12); -- sfix12_En11
  CONSTANT coeff8                         : signed(11 DOWNTO 0) := to_signed(401, 12); -- sfix12_En11
  CONSTANT coeff9                         : signed(11 DOWNTO 0) := to_signed(690, 12); -- sfix12_En11
  CONSTANT coeff10                        : signed(11 DOWNTO 0) := to_signed(401, 12); -- sfix12_En11
  CONSTANT coeff11                        : signed(11 DOWNTO 0) := to_signed(-41, 12); -- sfix12_En11
  CONSTANT coeff12                        : signed(11 DOWNTO 0) := to_signed(-110, 12); -- sfix12_En11
  CONSTANT coeff13                        : signed(11 DOWNTO 0) := to_signed(34, 12); -- sfix12_En11
  CONSTANT coeff14                        : signed(11 DOWNTO 0) := to_signed(42, 12); -- sfix12_En11
  CONSTANT coeff15                        : signed(11 DOWNTO 0) := to_signed(-24, 12); -- sfix12_En11
  CONSTANT coeff16                        : signed(11 DOWNTO 0) := to_signed(-12, 12); -- sfix12_En11
  CONSTANT coeff17                        : signed(11 DOWNTO 0) := to_signed(14, 12); -- sfix12_En11

  -- Signals
  SIGNAL QPSK_SRRC_in_re_regtype_re       : signed(7 DOWNTO 0); -- sfix8
  SIGNAL QPSK_SRRC_in_re_regtype_im       : signed(7 DOWNTO 0); -- sfix8
  SIGNAL delay_pipeline_re                : delay_pipeline_type(0 TO 15); -- sfix25_En11
  SIGNAL delay_pipeline_im                : delay_pipeline_type(0 TO 15); -- sfix25_En11
  SIGNAL sumvector_re                     : delay_pipeline_type(0 TO 15); -- sfix25_En11
  SIGNAL sumvector_im                     : delay_pipeline_type(0 TO 15); -- sfix25_En11
  SIGNAL product9_re                      : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product9_im                      : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product10_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product10_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product11_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product11_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product12_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product12_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product13_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product13_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product14_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product14_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product15_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product15_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product16_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product16_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product17_re                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL product17_im                     : signed(19 DOWNTO 0); -- sfix20_En11
  SIGNAL finalsum_re                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL finalsum_im                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast                         : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_1                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp                         : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_2                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_3                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_1                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_4                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_5                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_2                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_6                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_7                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_3                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_8                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_9                       : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_4                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_10                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_11                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_5                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_12                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_13                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_6                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_14                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_15                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_7                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_16                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_17                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_8                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_18                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_19                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_9                       : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_20                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_21                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_10                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_22                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_23                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_11                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_24                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_25                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_12                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_26                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_27                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_13                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_28                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_29                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_14                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_30                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_31                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_15                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_32                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_33                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_16                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_34                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_35                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_17                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_36                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_37                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_18                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_38                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_39                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_19                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_40                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_41                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_20                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_42                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_43                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_21                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_44                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_45                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_22                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_46                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_47                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_23                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_48                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_49                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_24                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_50                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_51                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_25                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_52                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_53                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_26                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_54                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_55                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_27                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_56                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_57                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_28                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_58                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_59                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_29                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_60                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_61                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_30                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL add_cast_62                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_cast_63                      : signed(24 DOWNTO 0); -- sfix25_En11
  SIGNAL add_temp_31                      : signed(25 DOWNTO 0); -- sfix26_En11
  SIGNAL output_typeconvert_re            : signed(11 DOWNTO 0); -- sfix12_En11
  SIGNAL output_typeconvert_im            : signed(11 DOWNTO 0); -- sfix12_En11


BEGIN

  -- Block Statements
  QPSK_SRRC_in_re_regtype_re <= signed(QPSK_SRRC_in_re);
  QPSK_SRRC_in_re_regtype_im <= signed(QPSK_SRRC_in_im);

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline_re <= (OTHERS => (OTHERS => '0'));
      delay_pipeline_im <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb_gated = '1' THEN
        delay_pipeline_re(0 TO 15) <= sumvector_re(0 TO 15);
        delay_pipeline_im(0 TO 15) <= sumvector_im(0 TO 15);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  product9_re <= QPSK_SRRC_in_re_regtype_re * coeff9;

  product9_im <= QPSK_SRRC_in_re_regtype_im * coeff9;

  product10_re <= QPSK_SRRC_in_re_regtype_re * coeff10;

  product10_im <= QPSK_SRRC_in_re_regtype_im * coeff10;

  product11_re <= QPSK_SRRC_in_re_regtype_re * coeff11;

  product11_im <= QPSK_SRRC_in_re_regtype_im * coeff11;

  product12_re <= QPSK_SRRC_in_re_regtype_re * coeff12;

  product12_im <= QPSK_SRRC_in_re_regtype_im * coeff12;

  product13_re <= QPSK_SRRC_in_re_regtype_re * coeff13;

  product13_im <= QPSK_SRRC_in_re_regtype_im * coeff13;

  product14_re <= QPSK_SRRC_in_re_regtype_re * coeff14;

  product14_im <= QPSK_SRRC_in_re_regtype_im * coeff14;

  product15_re <= QPSK_SRRC_in_re_regtype_re * coeff15;

  product15_im <= QPSK_SRRC_in_re_regtype_im * coeff15;

  product16_re <= QPSK_SRRC_in_re_regtype_re * coeff16;

  product16_im <= QPSK_SRRC_in_re_regtype_im * coeff16;

  product17_re <= QPSK_SRRC_in_re_regtype_re * coeff17;

  product17_im <= QPSK_SRRC_in_re_regtype_im * coeff17;

  add_cast <= resize(product17_re, 25);
  add_cast_1 <= delay_pipeline_re(0);
  add_temp <= resize(add_cast, 26) + resize(add_cast_1, 26);
  finalsum_re <= add_temp(24 DOWNTO 0);

  add_cast_2 <= resize(product17_im, 25);
  add_cast_3 <= delay_pipeline_im(0);
  add_temp_1 <= resize(add_cast_2, 26) + resize(add_cast_3, 26);
  finalsum_im <= add_temp_1(24 DOWNTO 0);

  add_cast_4 <= resize(product16_re, 25);
  add_cast_5 <= delay_pipeline_re(1);
  add_temp_2 <= resize(add_cast_4, 26) + resize(add_cast_5, 26);
  sumvector_re(0) <= add_temp_2(24 DOWNTO 0);

  add_cast_6 <= resize(product16_im, 25);
  add_cast_7 <= delay_pipeline_im(1);
  add_temp_3 <= resize(add_cast_6, 26) + resize(add_cast_7, 26);
  sumvector_im(0) <= add_temp_3(24 DOWNTO 0);

  add_cast_8 <= resize(product15_re, 25);
  add_cast_9 <= delay_pipeline_re(2);
  add_temp_4 <= resize(add_cast_8, 26) + resize(add_cast_9, 26);
  sumvector_re(1) <= add_temp_4(24 DOWNTO 0);

  add_cast_10 <= resize(product15_im, 25);
  add_cast_11 <= delay_pipeline_im(2);
  add_temp_5 <= resize(add_cast_10, 26) + resize(add_cast_11, 26);
  sumvector_im(1) <= add_temp_5(24 DOWNTO 0);

  add_cast_12 <= resize(product14_re, 25);
  add_cast_13 <= delay_pipeline_re(3);
  add_temp_6 <= resize(add_cast_12, 26) + resize(add_cast_13, 26);
  sumvector_re(2) <= add_temp_6(24 DOWNTO 0);

  add_cast_14 <= resize(product14_im, 25);
  add_cast_15 <= delay_pipeline_im(3);
  add_temp_7 <= resize(add_cast_14, 26) + resize(add_cast_15, 26);
  sumvector_im(2) <= add_temp_7(24 DOWNTO 0);

  add_cast_16 <= resize(product13_re, 25);
  add_cast_17 <= delay_pipeline_re(4);
  add_temp_8 <= resize(add_cast_16, 26) + resize(add_cast_17, 26);
  sumvector_re(3) <= add_temp_8(24 DOWNTO 0);

  add_cast_18 <= resize(product13_im, 25);
  add_cast_19 <= delay_pipeline_im(4);
  add_temp_9 <= resize(add_cast_18, 26) + resize(add_cast_19, 26);
  sumvector_im(3) <= add_temp_9(24 DOWNTO 0);

  add_cast_20 <= resize(product12_re, 25);
  add_cast_21 <= delay_pipeline_re(5);
  add_temp_10 <= resize(add_cast_20, 26) + resize(add_cast_21, 26);
  sumvector_re(4) <= add_temp_10(24 DOWNTO 0);

  add_cast_22 <= resize(product12_im, 25);
  add_cast_23 <= delay_pipeline_im(5);
  add_temp_11 <= resize(add_cast_22, 26) + resize(add_cast_23, 26);
  sumvector_im(4) <= add_temp_11(24 DOWNTO 0);

  add_cast_24 <= resize(product11_re, 25);
  add_cast_25 <= delay_pipeline_re(6);
  add_temp_12 <= resize(add_cast_24, 26) + resize(add_cast_25, 26);
  sumvector_re(5) <= add_temp_12(24 DOWNTO 0);

  add_cast_26 <= resize(product11_im, 25);
  add_cast_27 <= delay_pipeline_im(6);
  add_temp_13 <= resize(add_cast_26, 26) + resize(add_cast_27, 26);
  sumvector_im(5) <= add_temp_13(24 DOWNTO 0);

  add_cast_28 <= resize(product10_re, 25);
  add_cast_29 <= delay_pipeline_re(7);
  add_temp_14 <= resize(add_cast_28, 26) + resize(add_cast_29, 26);
  sumvector_re(6) <= add_temp_14(24 DOWNTO 0);

  add_cast_30 <= resize(product10_im, 25);
  add_cast_31 <= delay_pipeline_im(7);
  add_temp_15 <= resize(add_cast_30, 26) + resize(add_cast_31, 26);
  sumvector_im(6) <= add_temp_15(24 DOWNTO 0);

  add_cast_32 <= resize(product9_re, 25);
  add_cast_33 <= delay_pipeline_re(8);
  add_temp_16 <= resize(add_cast_32, 26) + resize(add_cast_33, 26);
  sumvector_re(7) <= add_temp_16(24 DOWNTO 0);

  add_cast_34 <= resize(product9_im, 25);
  add_cast_35 <= delay_pipeline_im(8);
  add_temp_17 <= resize(add_cast_34, 26) + resize(add_cast_35, 26);
  sumvector_im(7) <= add_temp_17(24 DOWNTO 0);

  add_cast_36 <= resize(product10_re, 25);
  add_cast_37 <= delay_pipeline_re(9);
  add_temp_18 <= resize(add_cast_36, 26) + resize(add_cast_37, 26);
  sumvector_re(8) <= add_temp_18(24 DOWNTO 0);

  add_cast_38 <= resize(product10_im, 25);
  add_cast_39 <= delay_pipeline_im(9);
  add_temp_19 <= resize(add_cast_38, 26) + resize(add_cast_39, 26);
  sumvector_im(8) <= add_temp_19(24 DOWNTO 0);

  add_cast_40 <= resize(product11_re, 25);
  add_cast_41 <= delay_pipeline_re(10);
  add_temp_20 <= resize(add_cast_40, 26) + resize(add_cast_41, 26);
  sumvector_re(9) <= add_temp_20(24 DOWNTO 0);

  add_cast_42 <= resize(product11_im, 25);
  add_cast_43 <= delay_pipeline_im(10);
  add_temp_21 <= resize(add_cast_42, 26) + resize(add_cast_43, 26);
  sumvector_im(9) <= add_temp_21(24 DOWNTO 0);

  add_cast_44 <= resize(product12_re, 25);
  add_cast_45 <= delay_pipeline_re(11);
  add_temp_22 <= resize(add_cast_44, 26) + resize(add_cast_45, 26);
  sumvector_re(10) <= add_temp_22(24 DOWNTO 0);

  add_cast_46 <= resize(product12_im, 25);
  add_cast_47 <= delay_pipeline_im(11);
  add_temp_23 <= resize(add_cast_46, 26) + resize(add_cast_47, 26);
  sumvector_im(10) <= add_temp_23(24 DOWNTO 0);

  add_cast_48 <= resize(product13_re, 25);
  add_cast_49 <= delay_pipeline_re(12);
  add_temp_24 <= resize(add_cast_48, 26) + resize(add_cast_49, 26);
  sumvector_re(11) <= add_temp_24(24 DOWNTO 0);

  add_cast_50 <= resize(product13_im, 25);
  add_cast_51 <= delay_pipeline_im(12);
  add_temp_25 <= resize(add_cast_50, 26) + resize(add_cast_51, 26);
  sumvector_im(11) <= add_temp_25(24 DOWNTO 0);

  add_cast_52 <= resize(product14_re, 25);
  add_cast_53 <= delay_pipeline_re(13);
  add_temp_26 <= resize(add_cast_52, 26) + resize(add_cast_53, 26);
  sumvector_re(12) <= add_temp_26(24 DOWNTO 0);

  add_cast_54 <= resize(product14_im, 25);
  add_cast_55 <= delay_pipeline_im(13);
  add_temp_27 <= resize(add_cast_54, 26) + resize(add_cast_55, 26);
  sumvector_im(12) <= add_temp_27(24 DOWNTO 0);

  add_cast_56 <= resize(product15_re, 25);
  add_cast_57 <= delay_pipeline_re(14);
  add_temp_28 <= resize(add_cast_56, 26) + resize(add_cast_57, 26);
  sumvector_re(13) <= add_temp_28(24 DOWNTO 0);

  add_cast_58 <= resize(product15_im, 25);
  add_cast_59 <= delay_pipeline_im(14);
  add_temp_29 <= resize(add_cast_58, 26) + resize(add_cast_59, 26);
  sumvector_im(13) <= add_temp_29(24 DOWNTO 0);

  add_cast_60 <= resize(product16_re, 25);
  add_cast_61 <= delay_pipeline_re(15);
  add_temp_30 <= resize(add_cast_60, 26) + resize(add_cast_61, 26);
  sumvector_re(14) <= add_temp_30(24 DOWNTO 0);

  add_cast_62 <= resize(product16_im, 25);
  add_cast_63 <= delay_pipeline_im(15);
  add_temp_31 <= resize(add_cast_62, 26) + resize(add_cast_63, 26);
  sumvector_im(14) <= add_temp_31(24 DOWNTO 0);

  sumvector_re(15) <= resize(product17_re, 25);
  sumvector_im(15) <= resize(product17_im, 25);

  output_typeconvert_re <= finalsum_re(11 DOWNTO 0);
  output_typeconvert_im <= finalsum_im(11 DOWNTO 0);

  -- Assignment Statements
  QPSK_SRRC_out_re <= std_logic_vector(output_typeconvert_re);
  QPSK_SRRC_out_im <= std_logic_vector(output_typeconvert_im);
END rtl;
